name: iiplab application deployment

run-name: Run with ${{ github.sha }} commit by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      deployUrl:
        description: 'git url'
        required: true
        default: 'https://github.com/gachon-iiplab/docker-images.git'
        type: string
      filename:
        description: '위 깃헙에서 실행시킬 파일의 이름'
        required: false
        default: 'main.py'
        type: string
      onlyDeploy:
        description: '빌드를 하지 않고 배포만 할지'
        required: false
        default: 'false'
        type: boolean
      dockerTags:
        description: '빌드 / 배포할 환경의 docker tag'
        required: false
        default: 'leesaebom/iiplab:latest'
        type: string
   
          
jobs:
  checkParameters:
    runs-on: ubuntu-latest
    steps:
    - run : echo "deployUrl ${{ github.event.inputs.deployUrl }}"
    - run : echo "onlyDeploy ${{ github.event.inputs.filename }}"
    - run : echo "onlyDeploy ${{ inputs.onlyDeploy }}"
    - run : echo "dockerTags ${{ github.event.inputs.dockerTags }}"
  dockerBuild:
    needs: checkParameters
    runs-on: iiplab
    steps:
    - run: cd ${{ github.workspace }}
    - uses: docker/login-action@v3.1.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        # Username used to log against the Docker registry
        username: leesaebom
        # Password or personal access token used to log against the Docker registry
        password: dckr_pat_gA4qT_k77o0rYgBp51MXUWubN8E
    - uses: actions/checkout@v4.1.2
      with:
        repository: ${{ github.repository }}
        # The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.  Otherwise, uses the default branch.
        ref: main
    - run: |
           docker build --build-arg GIT_URL=${{ github.event.inputs.deployUrl }} --build-arg FILENAME=${{ github.event.inputs.filename }} -t ${{ github.event.inputs.dockerTags  }} ./base
    - run: docker push ${{ github.event.inputs.dockerTags  }}
  dockerDeploy:
    needs: dockerBuild
    runs-on: iiplab
    steps:
      - uses: docker/login-action@v3.1.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          # Username used to log against the Docker registry
          username: leesaebom
          # Password or personal access token used to log against the Docker registry
          password: dckr_pat_gA4qT_k77o0rYgBp51MXUWubN8E
      - run: docker pull ${{ github.event.inputs.dockerTags  }}
      - run: ls -la
              
