name: iiplab application deployment.

run-name: Run with ${{ github.sha }} commit by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      deployUrl:
        description: 'git url'
        required: true
        default: 'https://github.com/gachon-iiplab/docker-images.git'
        type: string
      onlyDeploy:
        description: '빌드를 하지 않고 배포만 할지'
        required: false
        default: 'false'
        type: boolean
      dockerTags:
        description: '빌드 / 배포할 환경의 docker tag'
        required: false
        default: 'leesaebom/iiplab:tagname'
        type: string

jobs:
  checkParameters:
    runs-on: ubuntu-latest
    steps:
    - run : echo "deployUrl ${{ github.event.inputs.deployUrl }}"
    - run : echo "onlyDeploy ${{ inputs.onlyDeploy }}"
    - run : echo "dockerTags ${{ github.event.inputs.dockerTags }}"
  dockerBuild:
    if: ${{ github.event.inputs.onlyDeploy }} == false
    runs-on: ubuntu-latest
    steps:
    - run: echo Hello world!
