name: iiplab application only deployment

run-name: Run application by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      dockerTags:
        description: '배포할 환경의 docker tag'
        required: true
        default: 'leesaebom/iiplab:latest'
        type: string
          
jobs:
  checkParameters:
    runs-on: ubuntu-latest
    steps:
    - run : echo "deployUrl ${{ github.event.inputs.deployUrl }}"
    - run : echo "deployBranch ${{ github.event.inputs.deployBranch }}"
    - run : echo "onlyDeploy ${{ github.event.inputs.filename }}"
    - run : echo "dockerTags ${{ github.event.inputs.dockerTags }}"
  dockerDeploy:
    needs: checkParameters
    runs-on: iiplab
    steps:
      - uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker pull ${{ github.event.inputs.dockerTags  }}
      - run: docker run --rm -v dataset:/home/iiplab/dataset/ --gpus all ${{ github.event.inputs.dockerTags }}
