on:
  workflow_dispatch:
    inputs:
      deployUrl:
        description: 'git url'
        required: true
        default: ''
        type: string
      onlyDeploy:
        description: '빌드와 배포까지 할지, 배포만 할지'
        required: false
        default: 'false'
        type: boolean
      dockerTags:
        description: '빌드 / 배포할 환경의 docker tag'
        required: false
        type: string
